// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/index.ts", "bin/*.{ts,js}"],
    project: ["src/**/*.ts", "bin/**/*.{ts,js}"],
    ignoreBinaries: ["knip"],
    ignoreDependencies: ["@rad/config", "commander"],
    ignore: ["src/cli/**"],
});
