// Generated by monorepo-scripts/generate-knip-config.mts
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "../../monorepo-scripts/knip-defaults.js";

export default defineKnipConfig({
    entry: ["src/index.ts", "bin/*.{ts,js}"],
    project: ["src/**/*.ts", "bin/**/*.{ts,js}"],
    ignoreBinaries: ["knip"],
    ignoreDependencies: ["@rad/config", "commander"],
    ignore: ["src/cli/**"],
});
